// <auto-generated />
using ASPNET_MVC_MolvenoReservationApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNET_MVC_MolvenoReservationApplication.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("_guestEmail")
                        .HasMaxLength(100);

                    b.Property<string>("_guestName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("_guestPhone")
                        .HasMaxLength(20);

                    b.HasKey("GuestID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("_resComments");

                    b.Property<string>("_resDateOfReservation")
                        .IsRequired();

                    b.Property<int>("_resDurationOfReservation");

                    b.Property<int?>("_resGuestGuestID");

                    b.Property<int>("_resHourOfReservation");

                    b.Property<int>("_resMinuteOfReservation");

                    b.Property<int>("_resPartySize");

                    b.HasKey("ReservationID");

                    b.HasIndex("_resGuestGuestID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.ReservationTableCoupling", b =>
                {
                    b.Property<int>("ReservationTableCouplingID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ReservationID");

                    b.Property<int?>("TableID");

                    b.HasKey("ReservationTableCouplingID");

                    b.HasIndex("ReservationID");

                    b.HasIndex("TableID");

                    b.ToTable("ReservationTableCouplings");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("_tableArea");

                    b.Property<int>("_tableCapacity");

                    b.HasKey("TableID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.Reservation", b =>
                {
                    b.HasOne("ASPNET_MVC_MolvenoReservationApplication.Models.Guest", "_resGuest")
                        .WithMany()
                        .HasForeignKey("_resGuestGuestID");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Models.ReservationTableCoupling", b =>
                {
                    b.HasOne("ASPNET_MVC_MolvenoReservationApplication.Models.Reservation", "Reservation")
                        .WithMany("_resReservationTableCouplings")
                        .HasForeignKey("ReservationID");

                    b.HasOne("ASPNET_MVC_MolvenoReservationApplication.Models.Table", "Table")
                        .WithMany("_tableReservationTableCouplings")
                        .HasForeignKey("TableID");
                });
#pragma warning restore 612, 618
        }
    }
}
