// <auto-generated />
using ASPNET_MVC_MolvenoReservationApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNET_MVC_MolvenoReservationApplication.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("_guestEmail")
                        .HasMaxLength(40);

                    b.Property<string>("_guestName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("_guestPhone")
                        .HasMaxLength(13);

                    b.HasKey("GuestID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("_resArrivingTime");

                    b.Property<string>("_resComments");

                    b.Property<int?>("_resGuestGuestID");

                    b.Property<bool>("_resHidePrices");

                    b.Property<DateTime>("_resLeavingTime");

                    b.Property<int>("_resPartySize");

                    b.Property<int?>("_resTableTableID");

                    b.HasKey("ReservationID");

                    b.HasIndex("_resGuestGuestID");

                    b.HasIndex("_resTableTableID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("_tableArea");

                    b.Property<int>("_tableCapacity");

                    b.HasKey("TableID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("ASPNET_MVC_MolvenoReservationApplication.Reservation", b =>
                {
                    b.HasOne("ASPNET_MVC_MolvenoReservationApplication.Guest", "_resGuest")
                        .WithMany()
                        .HasForeignKey("_resGuestGuestID");

                    b.HasOne("ASPNET_MVC_MolvenoReservationApplication.Table", "_resTable")
                        .WithMany()
                        .HasForeignKey("_resTableTableID");
                });
#pragma warning restore 612, 618
        }
    }
}
